name: strapi
on: [pull_request]
jobs:
  strapi-unit-tests:
    if: contains(github.event.pull_request.labels.*.name, 'strapi')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - working-directory: ./backend/app
        run: |
          npm ci
          npm install jest
          npm run test
